In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set(rc={"figure.figsize":(30,15)})
pd.pandas.set_option("display.max_columns",None)

In [63]:
df = pd.read_csv('D:/ml_assignment_code/ml_assignment_code/data/ObesityDataSet_raw_and_data_sinthetic.csv')
df_copy = df.copy()

In [64]:
df_copy.shape

(2111, 17)

In [65]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Gender                          2111 non-null   object 
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object 
 5   FAVC                            2111 non-null   object 
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object 
 9   SMOKE                           2111 non-null   object 
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object 
 12  FAF                             21

In [66]:
df_copy.describe()

Age       Height       Weight         FCVC          NCP  \
count  2111.000000  2111.000000  2111.000000  2111.000000  2111.000000   
mean     24.312600     1.701677    86.586058     2.419043     2.685628   
std       6.345968     0.093305    26.191172     0.533927     0.778039   
min      14.000000     1.450000    39.000000     1.000000     1.000000   
25%      19.947192     1.630000    65.473343     2.000000     2.658738   
50%      22.777890     1.700499    83.000000     2.385502     3.000000   
75%      26.000000     1.768464   107.430682     3.000000     3.000000   
max      61.000000     1.980000   173.000000     3.000000     4.000000   

              CH2O          FAF          TUE  
count  2111.000000  2111.000000  2111.000000  
mean      2.008011     1.010298     0.657866  
std       0.612953     0.850592     0.608927  
min       1.000000     0.000000     0.000000  
25%       1.584812     0.124505     0.000000  
50%       2.000000     1.000000     0.625350  
75%       2.477420     1.666678     1.000000  
max       3.000000     3.000000     2.000000

In [67]:
df_copy.duplicated().sum()

24

In [68]:
df_copy = df_copy.drop_duplicates()

In [69]:
numerical_feature = [feature for feature in df_copy.columns if df_copy[feature].dtypes != 'O']
discrete_feature=[feature for feature in numerical_feature if len(df_copy[feature].unique())<25]
continuous_feature = [feature for feature in numerical_feature if feature not in discrete_feature]
categorical_feature = [feature for feature in df_copy.columns if feature not in numerical_feature]

In [70]:
continuous_feature

['Age', 'Height', 'Weight', 'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE']

In [71]:
categorical_feature

['Gender',
 'family_history_with_overweight',
 'FAVC',
 'CAEC',
 'SMOKE',
 'SCC',
 'CALC',
 'MTRANS',
 'NObeyesdad']

In [72]:

gender_map = {'Female':0,'Male':1}
family_history_with_overweight_map = {'no':0,'yes':1}
FAVC_map = {'no':0,'yes':1}
SMOKE_map = {'no':0,'yes':1}
SCC_map = {'no':0,'yes':1}
CAEC_map = {'no':0, 'Sometimes':1, 'Frequently':2, 'Always':3}
CALC_map = {'no':0, 'Sometimes':1, 'Frequently':2, 'Always':3}
MTRANS_map = {'Public_Transportation':0, 'Walking':1, 'Automobile':2, 'Motorbike':3, 'Bike':4}
NObeyesdad_map = {'Normal_Weight':0, 'Overweight_Level_I':1, 'Overweight_Level_II':2,
 'Obesity_Type_I':3, 'Insufficient_Weight':4, 'Obesity_Type_II':5,
 'Obesity_Type_III':6}

df_copy['Gender'] = df_copy['Gender'].map(gender_map)
df_copy['family_history_with_overweight'] = df_copy['family_history_with_overweight'].map(family_history_with_overweight_map)
df_copy['FAVC'] = df_copy['FAVC'].map(FAVC_map)
df_copy['SMOKE'] = df_copy['SMOKE'].map(SMOKE_map)
df_copy['SCC'] = df_copy['SCC'].map(SCC_map)
df_copy['CAEC'] = df_copy['CAEC'].map(CAEC_map)
df_copy['CALC'] = df_copy['CALC'].map(CALC_map)
df_copy['MTRANS'] = df_copy['MTRANS'].map(MTRANS_map)
df_copy['NObeyesdad'] = df_copy['NObeyesdad'].map(NObeyesdad_map)



In [73]:
X = df_copy.drop("NObeyesdad",axis=1)
y = df_copy['NObeyesdad']

In [74]:
numerical_cols = X.columns

In [75]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.model_selection import GridSearchCV
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [76]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler(with_mean=False))
    ]
)

preprocessor=ColumnTransformer([
('num_pipeline',num_pipeline,numerical_cols)
])

In [77]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=30)

In [78]:
X_train.shape

(1460, 16)

In [79]:
X_test.shape

(627, 16)

In [80]:
y_train.shape

(1460,)

In [81]:
y_test.shape

(627,)

In [82]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [83]:

from sklearn.linear_model import LogisticRegression

In [84]:
modal= LogisticRegression()
modal.fit(X_train,y_train)

c:\Users\himanshu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [85]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [86]:
y_pred2 = modal.predict(X_test)
print(confusion_matrix(y_test,y_pred2),'confusion_matrix')
print(accuracy_score(y_test,y_pred2),'accuracy_score')
print(classification_report(y_test,y_pred2),'classification_report')

[[ 43  10   8   0  17   0   0]
 [ 10  49   8   1   0   0   0]
 [  1  13  60  22   0   1   0]
 [  0   0   3  94   0   8   3]
 [  7   0   0   0  70   0   0]
 [  0   0   0   1   0  91   0]
 [  0   0   0   1   0   0 106]] confusion_matrix
0.8181818181818182 accuracy_score
              precision    recall  f1-score   support

           0       0.70      0.55      0.62        78
           1       0.68      0.72      0.70        68
           2       0.76      0.62      0.68        97
           3       0.79      0.87      0.83       108
           4       0.80      0.91      0.85        77
           5       0.91      0.99      0.95        92
           6       0.97      0.99      0.98       107

    accuracy                           0.82       627
   macro avg       0.80      0.81      0.80       627
weighted avg       0.81      0.82      0.81       627
 classification_report


In [87]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.svm import LinearSVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import StackingClassifier
from sklearn.ensemble import GradientBoostingClassifier


In [88]:
models = {
    "LogisticRegression": LogisticRegression(),
    'RandomForest':RandomForestClassifier(max_depth=4, random_state=0,oob_score=True),
    "DecisionTree":DecisionTreeClassifier(),
    "svc": LinearSVC()
}
trained_model_list=[]
model_list=[]
accuracy_score_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    #Make Predictions
    y_pred=model.predict(X_test)


    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print(accuracy_score(y_test,y_pred2),'accuracy_score')
    accuracy_score_list.append(accuracy_score(y_test,y_pred2))

    print('Model Training Performance')
    print('training accuracy',model.score(X_train,y_train))
    
    print('='*35)
    print('\n')

c:\Users\himanshu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression
0.8181818181818182 accuracy_score
Model Training Performance
training accuracy 0.8486301369863014


RandomForest
0.8181818181818182 accuracy_score
Model Training Performance
training accuracy 0.8376712328767123


DecisionTree
0.8181818181818182 accuracy_score
Model Training Performance
training accuracy 1.0


svc
0.8181818181818182 accuracy_score
Model Training Performance
training accuracy 0.6746575342465754




c:\Users\himanshu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [99]:
params = {
    'max_depth': [3, 4, 5],
    'min_samples_split': [2, 3, 4],
    'min_samples_leaf': [1, 2, 3]
}

In [98]:
estimators = [
    ('linear_regression', DecisionTreeClassifier()),
    ('random_forest', RandomForestClassifier()),
    ('gradient_boosting', GradientBoostingClassifier())
]

In [100]:
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [5, 10, 15],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [102]:
models={
    # "grid_search": GridSearchCV(estimator=RandomForestClassifier, param_grid=param_grid, cv=5),
    "grid_search": GridSearchCV(DecisionTreeClassifier(), params, cv=5),
    'Bagging_randomforest': BaggingClassifier(estimator=RandomForestClassifier(max_depth=4, random_state=0),n_estimators=15, random_state=0),
    'Stacking_regressor': StackingClassifier(estimators=estimators, final_estimator=RandomForestClassifier(max_depth=4, random_state=0),cv=5)
}
trained_model_list=[]
model_list=[]
accuracy_score_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    #Make Predictions
    y_pred=model.predict(X_test)


    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print(accuracy_score(y_test,y_pred2),'accuracy_score')
    accuracy_score_list.append(accuracy_score(y_test,y_pred2))

    print('Model Training Performance')
    print('training accuracy',model.score(X_train,y_train))
    
    print('='*35)
    print('\n')

grid_search
0.8181818181818182 accuracy_score
Model Training Performance
training accuracy 0.8294520547945206


Bagging_randomforest
0.8181818181818182 accuracy_score
Model Training Performance
training accuracy 0.873972602739726


Stacking_regressor
0.8181818181818182 accuracy_score
Model Training Performance
training accuracy 1.0


